language: node_js
node_js:
    - "0.12"
    - "6"
    - "5"
    - "4"
cache:
  directories:
    - node_modules
before_script: npm prune
script: npm test

notifications:
  on_success: change
  on_failure: always

matrix:
  fast_finish: true