language: node_js
node_js:
    - "0.10"
    - "6"
    - "5"
    - "4"

before_script: npm i istanbul
script: npm run travis

notifications:
  on_success: change
  on_failure: always

matrix:
  fast_finish: true