language: node_js

os:
  - linux
  - osx

node_js:
  - 8
  - 7
  - 6
  - 5
  - 4

cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.nvm

before_script: npm link
script:
  - npm test
  - npm prune

notifications:
  on_success: change
  on_failure: always

matrix:
  fast_finish: true
