language: node_js
node_js:
    - "6"
    - "0.12"
    - "5"
    - "4"

cache:
  directories:
    - node_modules
    - ~/.npm

before_script:
  - npm i istanbul
  - npm link

script:
  - npm test

notifications:
  on_success: change
  on_failure: always

matrix:
  fast_finish: true