#!/usr/bin/env node
"use strict";

var cmd = require('commander'),
    mod = require('./lib/get-metablock');

cmd.description("Get the file's metablock")
    .option("-o, --outfile [path]", "Outout file (defaults to STDOUT)")
    .option("-p, --prepend", "If specified, the metablock will be prepended to the file as opposed to overriding it")
    .action(sourceFile => {
        mod.getBlock(sourceFile, (err, contents) => {
            if (err) {
                throw err;
            } else {
                console.log(contents);
            }
        });
    })
    .parse(process.argv);