#!/usr/bin/env node

require('commander')
    .description(require('./package.json').description)
    .command("get-metablock <sourceFile> [path]", "Get the file's metablock")
    .parse(process.argv);