#!/usr/bin/env node

var cmd = require('commander'),
    getBlock = require('../index').getMetablock;

cmd.description("Get the file's entire metablock")
    .option("-i, --infile <path>", "Input file (gets input from STDIN if omitted)")
    .option("-o, --outfile <path>", "Output file (defaults to STDOUT)")
    .action(function () {
        process.stderr.write("foo");
    })
    .parse(process.argv);