#!/usr/bin/env node

var cmd = require('commander'),
    getBlock = require('..').getMetablock;

cmd.description("Get the file's metablock")
    .option("-o, --outfile <path>", "Outout file (defaults to STDOUT)")
    .action(function (sourceFile) {
        getBlock(sourceFile, function (err, contents) {
            if (err) {
                throw err;
            } else if (cmd.outfile) {
                require('fs').writeFile(cmd.outfile, contents, 'utf8', function (err) {
                    if (err) {
                        throw err;
                    }
                });
            } else {
                process.stdout.write(contents);
            }
        });
    })
    .parse(process.argv);