#!/usr/bin/env node

var argv = require('minimist')(process.argv.slice(2), {
        alias: {
            h: 'help',
            i: 'infile',
            o: 'outfile'
        }
    }),
    mod = require('../../lib/get-metablock'),
    stdin = require('get-stdin'),
    common = require('../common'),
    helpfile = require('path').basename(__filename);

module.exports = function () {
    if (argv.help) {
        common.help(helpfile);
    } else if (argv.infile) {
        mod.fromFile(argv.infile, function (e, c) {
            if (e) {
                process.stderr.write(e.message);
            } else {
                common.doOut(argv, c);
            }
        });
    } else {
        stdin().then(function (input) {
            if (input) {
                mod.fromString(input, function (e, c) {
                    if (e) {
                        process.stderr.write(e.message);
                        process.exit(1);
                    } else {
                        common.doOut(argv, c);
                    }
                });
            } else {
                common.help(helpfile);
            }
        });
    }
};